// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[PrimaryKey("LoginProvider", "ProviderKey")]
public partial class AspNetUserLogins
{
    [Key]
    [StringLength(128)]
    public string LoginProvider { get; set; }

    [Key]
    [StringLength(128)]
    public string ProviderKey { get; set; }

    public string ProviderDisplayName { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AspNetUserLogins")]
    public virtual AspNetUsers User { get; set; }
}