// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[Table("auction")]
public partial class Auction
{
    public Auction()
    {
        
        Auctionbid = new HashSet<Auctionbid>();
    }
    [Key]
    [Column("id_auction")]
    public int IdAuction { get; set; }

    [Column("id_product")]
    public int? IdProduct { get; set; }

    [Column("beginbid")]
    public int Beginbid { get; set; }

    [Column("begintime")]
    public DateTime? Begintime { get; set; }

    [Column("endtime")]
    public DateTime? Endtime { get; set; }
    [NotMapped]
    public DateTime DateTime { get; set; } = DateTime.Now;
    [NotMapped]
    public TimeSpan Date1 { get; set; }
    
    

    [ForeignKey("IdProduct")]
    [InverseProperty("Auction")]
    public virtual Product IdProductNavigation { get; set; }

    [InverseProperty("IdAuctionNavigation")]
    public virtual ICollection<Auctionbid> Auctionbid { get; } = new List<Auctionbid>();
}