// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[Table("auction")]
public partial class Auction
{
    [Key]
    [Column("id_auction")]
    public int IdAuction { get; set; }

    [Column("id_product")]
    public int? IdProduct { get; set; }

    [Column("beginbid")]
    public int Beginbid { get; set; }

    [Column("begintime")]
    public DateTime? Begintime { get; set; }

    [Column("endtime")]
    public DateTime? Endtime { get; set; }

    [ForeignKey("IdProduct")]
    [InverseProperty("Auction")]
    public virtual Product IdProductNavigation { get; set; }
}