// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[Table("product")]
public partial class Product
{
    [Key]
    [Column("id_product")]
    public int IdProduct { get; set; }

    [Required]
    [Column("product_name")]
    [StringLength(200)]
    public string ProductName { get; set; }

    [Required]
    [Column("articul")]
    [StringLength(100)]
    public string Articul { get; set; }

    [Column("prise")]
    public int Prise { get; set; }

    [Column("description")]
    [StringLength(1000)]
    public string Description { get; set; }

    [Column("product_pic")]
    [StringLength(1000)]
    public string ProductPic { get; set; }

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<Auction> Auction { get; } = new List<Auction>();

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<Auctionbid> Auctionbid { get; } = new List<Auctionbid>();
}