// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[Table("product")]
public partial class Product
{
    public Product()
    {
        Auction = new HashSet<Auction>();
        Auctionbid = new HashSet<Auctionbid>();
    }
    [Key]
    [Column("id_product")]
    public int IdProduct { get; set; }

    [Required]
    [Column("product_name")]
    [StringLength(200)]
    public string ProductName { get; set; }

    [Required]
    [Column("articul")]
    [StringLength(100)]
    public string Articul { get; set; }

    [Column("prise")]
    public int Prise { get; set; }

    [Column("description")]
    [StringLength(1000)]
    public string Description { get; set; }

    [Required]
    [Column("product_pic")]
    [StringLength(1000)]
    public string ProductPic { get; set; }

    [Required]
    [Column("product_pic1")]
    [StringLength(1000)]
    public string ProductPic1 { get; set; }

    [Required]
    [Column("product_pic2")]
    [StringLength(1000)]
    public string ProductPic2 { get; set; }

    [Column("Photo1")]
    [Display(Name = "Выберите фотографию")]
    [NotMapped]
    public IFormFile Photo1 { get; set; }
    [Column("Photo2")]
    [NotMapped]
    [Display(Name = "Выберите фотографию")]
    public IFormFile Photo2 { get; set; }
    [Column("Photo3")]
    [NotMapped]
    [Display(Name = "Выберите фотографию")]
    public IFormFile Photo3 { get; set; }

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<Auction> Auction { get; } = new List<Auction>();

    [InverseProperty("IdProductNavigation")]
    public virtual ICollection<Auctionbid> Auctionbid { get; } = new List<Auctionbid>();
}